apiVersion: v1
kind: ConfigMap
metadata:
  name: asteroid-detector-app-code
  namespace: sensor-array
  labels:
    challenge: asteroid-detector
data:
  asteroid-detector.js: |
    const location = process.env.SCANNING_LOCATION;

    console.log('Asteroid Detector starting up...');

    setInterval(() => {
      console.log(`Scanning for asteroids in location: ${location}`);
      if (location === 'Alpha Centauri') {
        console.log('[ERROR] Asteroid swarm detected! ðŸŒ ');
      }
    }, 10000); // Check every 5 seconds
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: asteroid-detector-config
  namespace: sensor-array
  labels:
    challenge: asteroid-detector
data:
  scanning_location: "Alpha Centauri"
